// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectDaedalus.Infrastructure.Data;

#nullable disable

namespace ProjectDaedalus.Infrastructure.Migrations
{
    [DbContext(typeof(DaedalusContext))]
    partial class DaedalusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("ConnectionAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("connection_address");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("enum('USB','Bluetooth','WiFi')")
                        .HasColumnName("connection_type");

                    b.Property<string>("HardwareIdentifier")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("hardware_identifier");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_seen");

                    b.Property<string>("Status")
                        .HasColumnType("enum('Active','Inactive','Disconnected')")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("DeviceId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ConnectionAddress" }, "connection_address")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "fk_device");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("message");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int")
                        .HasColumnName("notification_type");

                    b.Property<int>("UserPlantId")
                        .HasColumnType("int")
                        .HasColumnName("userplant_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_notifications_created");

                    b.HasIndex("UserPlantId", "IsRead", "CreatedAt")
                        .HasDatabaseName("idx_notifications_userplant_read_created");

                    b.ToTable("notification");
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.NotificationHistory", b =>
                {
                    b.Property<int>("NotificationHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_history_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationHistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("MoistureValue")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("moisture_value");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int")
                        .HasColumnName("notification_type");

                    b.Property<decimal>("ThresholdValue")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("threshold_value");

                    b.Property<int>("UserPlantId")
                        .HasColumnType("int")
                        .HasColumnName("user_plant_id");

                    b.HasKey("NotificationHistoryId");

                    b.HasIndex("UserPlantId", "NotificationType")
                        .HasDatabaseName("idx_notification_history_dedup");

                    b.HasIndex("UserPlantId", "NotificationType", "CreatedAt")
                        .HasDatabaseName("idx_notification_history_userplant_type_created");

                    b.ToTable("notification_history");
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<string>("FamiliarName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("familiar_name");

                    b.Property<string>("FunFact")
                        .HasColumnType("text")
                        .HasColumnName("fun_fact");

                    b.Property<decimal>("MoistureHighRange")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("moisture_high_range");

                    b.Property<decimal>("MoistureLowRange")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("moisture_low_range");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("scientific_name");

                    b.HasKey("PlantId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ScientificName" }, "scientific_name")
                        .IsUnique();

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.SensorHistory", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp")
                        .HasColumnName("time_stamp");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<decimal>("MoistureLevel")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("moisture_level");

                    b.HasKey("TimeStamp", "DeviceId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "DeviceId" }, "fk_sensor_history");

                    b.ToTable("sensor_history", (string)null);
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.UserPlant", b =>
                {
                    b.Property<int>("UserPlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_plant_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserPlantId"));

                    b.Property<DateTime?>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("date_added")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UserPlantId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DeviceId" }, "fk_userplants_device");

                    b.HasIndex(new[] { "PlantId" }, "fk_userplants_plant");

                    b.HasIndex(new[] { "UserId", "DeviceId" }, "user_id")
                        .IsUnique();

                    b.ToTable("user_plants", (string)null);
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.Device", b =>
                {
                    b.HasOne("ProjectDaedalus.Core.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.Notification", b =>
                {
                    b.HasOne("ProjectDaedalus.Core.Entities.UserPlant", "UserPlant")
                        .WithMany("Notifications")
                        .HasForeignKey("UserPlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPlant");
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.NotificationHistory", b =>
                {
                    b.HasOne("ProjectDaedalus.Core.Entities.UserPlant", "UserPlant")
                        .WithMany("NotificationHistories")
                        .HasForeignKey("UserPlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPlant");
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.SensorHistory", b =>
                {
                    b.HasOne("ProjectDaedalus.Core.Entities.Device", "Device")
                        .WithMany("SensorHistories")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_history");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.UserPlant", b =>
                {
                    b.HasOne("ProjectDaedalus.Core.Entities.Device", "Device")
                        .WithMany("UserPlants")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_userplants_device");

                    b.HasOne("ProjectDaedalus.Core.Entities.Plant", "Plant")
                        .WithMany("UserPlants")
                        .HasForeignKey("PlantId")
                        .IsRequired()
                        .HasConstraintName("fk_userplants_plant");

                    b.HasOne("ProjectDaedalus.Core.Entities.User", "User")
                        .WithMany("UserPlants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_userplants_user");

                    b.Navigation("Device");

                    b.Navigation("Plant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.Device", b =>
                {
                    b.Navigation("SensorHistories");

                    b.Navigation("UserPlants");
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.Plant", b =>
                {
                    b.Navigation("UserPlants");
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("UserPlants");
                });

            modelBuilder.Entity("ProjectDaedalus.Core.Entities.UserPlant", b =>
                {
                    b.Navigation("NotificationHistories");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
